
include:
  - project: 'mbrandner-group/renovate-runner'
    file: '/templates/renovate-dind.gitlab-ci.yml' 
  #- template: Auto-DevOps.gitlab-ci.yml


variables:
  RENOVATE_GIT_AUTHOR: Renovate Bot <bot@renovate.com>
  RENOVATE_REQUIRE_CONFIG: optional
  KUBE_INGRESS_BASE_DOMAIN: 34.134.119.247.nip.io
  KUBE_CONTEXT: mbrandner-group/agentapril22:mirko-1
