image: docker:20.10.6
services:
  - name: 'docker:20.10.6-dind'

stages:
  - build
  - analyze
  - push
  - dast

variables:
  CI_DEBUG_TRACE: "true"

include:
  # - template: SAST.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

.build:
  stage: build
  image: maven:3-jdk-11-slim
  script:
    - mvn clean install -DskipTests
    - mvn package -DskipTests -Dmaven.repo.local=./.m2/
  cache:
    policy: push
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - .m2
  artifacts:
    paths:
      - "webgoat-server/Dockerfile"
      - "webgoat-server/target/webgoat-server-v8.1.0.jar"

.sast:
  stage: analyze
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - .m2/
      - target/
      - gl-sast-report.json

.spotbugs-sast:
  dependencies:
    - build
  script:
    - /analyzer run -compile=false
  variables:
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json

.push:
  services:
  - name: docker:20.10.6-dind
  image: docker:20.10.6
  variables:
    DOCKER_DRIVER: overlay2
  stage: push
  script:
    - cd webgoat-server
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --build-arg webgoat_version=v8.1.0 --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest



dast:
  variables:
    GIT_STRATEGY: fetch
    DAST_WEBSITE: http://webgoat:8080/WebGoat/
    DAST_AUTH_URL: http://webgoat:8080/WebGoat/login
    DAST_EXCLUDE_URLS: http://webgoat:8080/WebGoat/logout,http://webgoat:8080/WebGoat/login,http://webgoat:8080/WebGoat/login?logout
    DAST_FULL_SCAN_ENABLED: "true"
    DAST_USERNAME: testtest
    DAST_PASSWORD: password # use protected/masked variables, this is only for demonstration purposes
    DAST_USERNAME_FIELD: username
    DAST_PASSWORD_FIELD: password
    DAST_AUTH_REPORT: "true"
    DAST_AUTH_VERIFICATION_URL: "http://webgoat:8080/WebGoat/start.mvc#lesson/WebGoatIntroduction.lesson"
    GIT_STRATEGY: fetch

  before_script:
    - curl -vvv -X POST -d "username=testtest&password=password&matchingPassword=password&agree=agree&submit=Submit" "http://webgoat:8080/WebGoat/register.mvc"
    - export DAST_WEBSITE=http://webgoat:8080/WebGoat/ # do it again as the DAST template does crappy work
    - export DAST_AUTH_URL=http://webgoat:8080/WebGoat/login
    - export DAST_EXCLUDE_URLS=http://webgoat:8080/WebGoat/logout,http://webgoat:8080/WebGoat/login,http://webgoat:8080/WebGoat/login?logout
    - export DAST_FULL_SCAN_ENABLED=true
    - export DAST_USERNAME=testtest
    - export DAST_PASSWORD=password # use protected/masked variables, this is only for demonstration purposes
    - export DAST_USERNAME_FIELD=username
    - export DAST_PASSWORD_FIELD=password
    - export DAST_AUTH_REPORT=true
    - export DAST_AUTH_VERIFICATION_URL="http://webgoat:8080/WebGoat/start.mvc#lesson/WebGoatIntroduction.lesson"
   # - export DAST_ZAP_USE_AJAX_SPIDER=true
    #- export GIT_STRATEGY="fetch"
    #- export DAST_PATHS_FILE=dastpaths
    - export DAST_PATHS="/WebGoat/start.mvc#lesson/SqlInjection.lesson/1,/WebGoat/start.mvc#lesson/SqlInjection.lesson/2,/WebGoat/start.mvc#lesson/SqlInjection.lesson/3,/WebGoat/start.mvc#lesson/SqlInjection.lesson/4,/WebGoat/start.mvc#lesson/SqlInjection.lesson/5"
  artifacts:
    paths: [gl-dast-debug-auth-report.html]
    when: always
  variables:
    DOCKER_DRIVER: overlay2
  services:
  - name: $CI_REGISTRY_IMAGE:latest
    alias: webgoat
